import type { DemoVisa } from "./data";

export type DemoBeneficiary = {
  user: number;
  case: number;
  company: 1 | 2;
  name: string;
  nationality: string;
  jobTitle: string;
  department: string;
  workLocation: string;
  visa: DemoVisa;
  advisors?: number[];
};

// Fictional employee profiles. The case field identifies their original case; renewals are separate records.
// Work locations are destinations. Canadian ICT examples represent transfers from an overseas office.
// Proposed routes do not establish eligibility; no assessment result is inferred from a job title.
export const demoBeneficiaries: DemoBeneficiary[] = [
  {
    user: 2,
    case: 1,
    company: 1,
    name: "Alex Morgan",
    nationality: "Canada",
    jobTitle: "Software Engineer",
    department: "Engineering",
    workLocation: "New York, United States",
    visa: "h1b",
  },
  {
    user: 5,
    case: 2,
    company: 2,
    name: "Taylor Robinson",
    nationality: "United Kingdom",
    jobTitle: "Data Analyst",
    department: "Data & Analytics",
    workLocation: "Auckland, New Zealand",
    visa: "aewv",
  },
  {
    user: 10,
    case: 10,
    company: 1,
    name: "Priya Nair",
    nationality: "India",
    jobTitle: "Senior Software Engineer",
    department: "Engineering",
    workLocation: "Seattle, United States",
    visa: "h1b",
  },
  {
    user: 11,
    case: 11,
    company: 1,
    name: "Tomás Herrera",
    nationality: "Spain",
    jobTitle: "Head of Product",
    department: "Product",
    workLocation: "London, United Kingdom",
    visa: "globalTalent",
  },
  {
    user: 12,
    case: 12,
    company: 1,
    name: "Mei Lin",
    nationality: "China",
    jobTitle: "Data Scientist",
    department: "Data & Analytics",
    workLocation: "Sydney, Australia",
    visa: "skillsInDemand",
  },
  {
    user: 13,
    case: 13,
    company: 1,
    name: "Daniel Okafor",
    nationality: "Nigeria",
    jobTitle: "Regional Sales Director",
    department: "Sales",
    workLocation: "Toronto, Canada",
    visa: "intraCompany",
  },
  {
    user: 14,
    case: 14,
    company: 1,
    name: "Sofia Rossi",
    nationality: "Italy",
    jobTitle: "Product Designer",
    department: "Design",
    workLocation: "Wellington, New Zealand",
    visa: "aewv",
  },
  {
    user: 15,
    case: 15,
    company: 1,
    name: "Arjun Mehta",
    nationality: "India",
    jobTitle: "Machine Learning Engineer",
    department: "Engineering",
    workLocation: "Boston, United States",
    visa: "h1b",
  },
  {
    user: 16,
    case: 16,
    company: 1,
    name: "Hana Sato",
    nationality: "Japan",
    jobTitle: "Platform Engineer",
    department: "Engineering",
    workLocation: "Manchester, United Kingdom",
    visa: "skilledWorker",
  },
  {
    user: 17,
    case: 17,
    company: 1,
    name: "Liam O'Connor",
    nationality: "Ireland",
    jobTitle: "Director of Enterprise Sales",
    department: "Sales",
    workLocation: "Vancouver, Canada",
    visa: "intraCompany",
  },
  {
    user: 18,
    case: 18,
    company: 1,
    name: "Amara Mensah",
    nationality: "Ghana",
    jobTitle: "Operations Manager",
    department: "Operations",
    workLocation: "Auckland, New Zealand",
    visa: "aewv",
  },
  {
    user: 19,
    case: 19,
    company: 1,
    name: "Lucas Silva",
    nationality: "Brazil",
    jobTitle: "Frontend Engineer",
    department: "Engineering",
    workLocation: "Melbourne, Australia",
    visa: "skillsInDemand",
  },
  {
    user: 20,
    case: 20,
    company: 1,
    name: "Elena Petrova",
    nationality: "Bulgaria",
    jobTitle: "Principal Research Scientist",
    department: "Research",
    workLocation: "Cambridge, United Kingdom",
    visa: "globalTalent",
  },
  {
    user: 21,
    case: 21,
    company: 1,
    name: "Omar Hassan",
    nationality: "Egypt",
    jobTitle: "Technical Account Manager",
    department: "Customer Success",
    workLocation: "Wellington, New Zealand",
    visa: "aewv",
  },
  {
    user: 22,
    case: 22,
    company: 1,
    name: "Aisha Khan",
    nationality: "Pakistan",
    jobTitle: "Senior Product Designer",
    department: "Design",
    workLocation: "London, United Kingdom",
    visa: "skilledWorker",
  },
  {
    user: 23,
    case: 23,
    company: 1,
    name: "Noah Williams",
    nationality: "Australia",
    jobTitle: "Backend Engineer",
    department: "Engineering",
    workLocation: "Austin, United States",
    visa: "h1b",
  },
  {
    user: 24,
    case: 24,
    company: 1,
    name: "Isabella Costa",
    nationality: "Portugal",
    jobTitle: "Finance Analyst",
    department: "Finance",
    workLocation: "Sydney, Australia",
    visa: "skillsInDemand",
  },
  {
    user: 25,
    case: 25,
    company: 1,
    name: "Ethan Chen",
    nationality: "Taiwan",
    jobTitle: "Security Engineer",
    department: "Engineering",
    workLocation: "San Francisco, United States",
    visa: "h1b",
  },
  {
    user: 26,
    case: 26,
    company: 1,
    name: "Zara Ahmed",
    nationality: "Bangladesh",
    jobTitle: "People Operations Specialist",
    department: "People",
    workLocation: "Auckland, New Zealand",
    visa: "aewv",
  },
  {
    user: 27,
    case: 27,
    company: 1,
    name: "Mateo García",
    nationality: "Mexico",
    jobTitle: "QA Engineer",
    department: "Engineering",
    workLocation: "Birmingham, United Kingdom",
    visa: "skilledWorker",
  },
  {
    user: 28,
    case: 28,
    company: 2,
    name: "Chloe Martin",
    nationality: "France",
    jobTitle: "Customer Success Director",
    department: "Customer Success",
    workLocation: "Toronto, Canada",
    visa: "intraCompany",
  },
  {
    user: 29,
    case: 29,
    company: 2,
    name: "Ravi Patel",
    nationality: "India",
    jobTitle: "Data Engineer",
    department: "Data & Analytics",
    workLocation: "Chicago, United States",
    visa: "h1b",
  },
  {
    user: 30,
    case: 30,
    company: 2,
    name: "Fatima Ali",
    nationality: "Pakistan",
    jobTitle: "Marketing Manager",
    department: "Marketing",
    workLocation: "Wellington, New Zealand",
    visa: "aewv",
  },
  {
    user: 31,
    case: 31,
    company: 2,
    name: "Oliver Brown",
    nationality: "United Kingdom",
    jobTitle: "Solutions Architect",
    department: "Engineering",
    workLocation: "Sydney, Australia",
    visa: "skillsInDemand",
  },
  {
    user: 32,
    case: 32,
    company: 2,
    name: "Yuna Kim",
    nationality: "South Korea",
    jobTitle: "UX Researcher",
    department: "Design",
    workLocation: "London, United Kingdom",
    visa: "skilledWorker",
  },
  {
    user: 33,
    case: 33,
    company: 2,
    name: "Gabriel Santos",
    nationality: "Brazil",
    jobTitle: "Support Engineer",
    department: "Customer Success",
    workLocation: "Auckland, New Zealand",
    visa: "aewv",
  },
  {
    user: 34,
    case: 34,
    company: 2,
    name: "Leila Haddad",
    nationality: "Lebanon",
    jobTitle: "Business Analyst",
    department: "Operations",
    workLocation: "Melbourne, Australia",
    visa: "skillsInDemand",
  },
  {
    user: 35,
    case: 35,
    company: 2,
    name: "Oscar Jensen",
    nationality: "Denmark",
    jobTitle: "Engineering Director",
    department: "Engineering",
    workLocation: "Vancouver, Canada",
    visa: "intraCompany",
  },
  {
    user: 70,
    case: 50,
    company: 1,
    name: "Lydia James",
    nationality: "United Kingdom",
    jobTitle: "Software Engineer",
    department: "Engineering",
    workLocation: "Denver, United States",
    visa: "h1b",
    advisors: [3, 6],
  },
  {
    user: 71,
    case: 51,
    company: 1,
    name: "Marcus Reed",
    nationality: "United States",
    jobTitle: "Delivery Manager",
    department: "Operations",
    workLocation: "Auckland, New Zealand",
    visa: "aewv",
  },
  {
    user: 72,
    case: 52,
    company: 1,
    name: "Eva Novak",
    nationality: "Czech Republic",
    jobTitle: "Research Engineer",
    department: "Research",
    workLocation: "Boston, United States",
    visa: "h1b",
    advisors: [6],
  },
  {
    user: 73,
    case: 53,
    company: 2,
    name: "Leo Moreau",
    nationality: "France",
    jobTitle: "Software Engineer",
    department: "Engineering",
    workLocation: "Brisbane, Australia",
    visa: "skillsInDemand",
    advisors: [6],
  },
  {
    user: 60,
    case: 60,
    company: 1,
    name: "Nina Kapoor",
    nationality: "India",
    jobTitle: "Software Engineer",
    department: "Engineering",
    workLocation: "Seattle, United States",
    visa: "h1b",
  },
  {
    user: 61,
    case: 61,
    company: 1,
    name: "Ben Wilson",
    nationality: "South Africa",
    jobTitle: "Product Manager",
    department: "Product",
    workLocation: "London, United Kingdom",
    visa: "skilledWorker",
  },
  {
    user: 62,
    case: 62,
    company: 1,
    name: "Grace Liu",
    nationality: "China",
    jobTitle: "Data Analyst",
    department: "Data & Analytics",
    workLocation: "Melbourne, Australia",
    visa: "skillsInDemand",
  },
  {
    user: 63,
    case: 63,
    company: 2,
    name: "Diego Torres",
    nationality: "Mexico",
    jobTitle: "Operations Director",
    department: "Operations",
    workLocation: "Toronto, Canada",
    visa: "intraCompany",
  },
  {
    user: 74,
    case: 64,
    company: 1,
    name: "Ivy Tran",
    nationality: "Vietnam",
    jobTitle: "Business Analyst",
    department: "Operations",
    workLocation: "Wellington, New Zealand",
    visa: "aewv",
  },
];
