import type { Workflow } from "./workflows";

export type CasePlan = {
  case: number;
  employee: number;
  status:
    | "Pre-assessment"
    | "In progress"
    | "Filed"
    | "Approved"
    | "RFE Issued";
  created: number;
  updated: number;
  filed?: number;
  approved?: number;
  expires?: number;
  passport?: number | null;
  task?: Workflow;
  target?: number | null;
  advisors: number[];
};

// Day offsets describe fictional recorded events relative to the seed snapshot.
// created/updated/filed/approved are days ago; expires/passport/target are days from it.
// Every open task has an explicit owner and an internal target, or an unknown target.
export const casePlans: CasePlan[] = [
  {
    case: 1,
    employee: 2,
    status: "RFE Issued",
    created: 96,
    filed: 64,
    updated: 8,
    passport: 920,
    task: "rfe",
    target: 7,
    advisors: [3],
  },
  {
    case: 2,
    employee: 5,
    status: "Filed",
    created: 47,
    filed: 12,
    updated: 3,
    passport: 1460,
    task: "filing",
    target: 2,
    advisors: [6],
  },
  {
    case: 10,
    employee: 10,
    status: "Approved",
    created: 890,
    filed: 850,
    approved: 790,
    updated: 6,
    expires: 28,
    passport: 630,
    advisors: [3],
  },
  {
    case: 11,
    employee: 11,
    status: "Pre-assessment",
    created: 9,
    updated: 2,
    passport: 1110,
    task: "assessment",
    target: 3,
    advisors: [3],
  },
  {
    case: 12,
    employee: 12,
    status: "Filed",
    created: 68,
    filed: 19,
    updated: 4,
    passport: 1980,
    advisors: [6],
  },
  {
    case: 13,
    employee: 13,
    status: "Pre-assessment",
    created: 8,
    updated: 1,
    passport: 1020,
    task: "roleBrief",
    target: 4,
    advisors: [3],
  },
  {
    case: 14,
    employee: 14,
    status: "Approved",
    created: 380,
    filed: 344,
    approved: 301,
    updated: 20,
    expires: 429,
    passport: 1420,
    advisors: [6],
  },
  {
    case: 15,
    employee: 15,
    status: "RFE Issued",
    created: 112,
    filed: 74,
    updated: 3,
    passport: 1240,
    task: "rfe",
    target: 12,
    advisors: [3],
  },
  {
    case: 16,
    employee: 16,
    status: "Filed",
    created: 59,
    filed: 16,
    updated: 5,
    passport: 1620,
    advisors: [3],
  },
  {
    case: 17,
    employee: 17,
    status: "Pre-assessment",
    created: 11,
    updated: 4,
    passport: 1230,
    task: "missingCv",
    target: -2,
    advisors: [3],
  },
  {
    case: 18,
    employee: 18,
    status: "In progress",
    created: 23,
    updated: 2,
    passport: 1600,
    task: "employerReview",
    target: 6,
    advisors: [6],
  },
  {
    case: 19,
    employee: 19,
    status: "Approved",
    created: 265,
    filed: 227,
    approved: 186,
    updated: 13,
    expires: 544,
    passport: 1540,
    advisors: [6],
  },
  {
    case: 20,
    employee: 20,
    status: "Filed",
    created: 82,
    filed: 21,
    updated: 6,
    passport: 1720,
    advisors: [3],
  },
  {
    case: 21,
    employee: 21,
    status: "Pre-assessment",
    created: 5,
    updated: 1,
    passport: 870,
    task: "assessment",
    target: 5,
    advisors: [6],
  },
  {
    case: 22,
    employee: 22,
    status: "In progress",
    created: 31,
    updated: 4,
    passport: 1290,
    task: "documents",
    target: 8,
    advisors: [3],
  },
  {
    case: 23,
    employee: 23,
    status: "Filed",
    created: 61,
    filed: 17,
    updated: 7,
    passport: 2030,
    advisors: [3],
  },
  {
    case: 24,
    employee: 24,
    status: "Approved",
    created: 340,
    filed: 302,
    approved: 261,
    updated: 40,
    expires: 469,
    passport: 1730,
    advisors: [6],
  },
  {
    case: 25,
    employee: 25,
    status: "RFE Issued",
    created: 148,
    filed: 103,
    updated: 41,
    passport: 1890,
    task: "rfe",
    target: -4,
    advisors: [3],
  },
  {
    case: 26,
    employee: 26,
    status: "Pre-assessment",
    created: 13,
    updated: 3,
    passport: null,
    task: "documents",
    target: 7,
    advisors: [6],
  },
  {
    case: 27,
    employee: 27,
    status: "In progress",
    created: 36,
    updated: 2,
    passport: 1150,
    task: "draft",
    target: 4,
    advisors: [3],
  },
  {
    case: 28,
    employee: 28,
    status: "Filed",
    created: 77,
    filed: 32,
    updated: 9,
    passport: 940,
    advisors: [3],
  },
  {
    case: 29,
    employee: 29,
    status: "Approved",
    created: 530,
    filed: 490,
    approved: 440,
    updated: 29,
    expires: 610,
    passport: 1260,
    advisors: [3],
  },
  {
    case: 30,
    employee: 30,
    status: "Pre-assessment",
    created: 7,
    updated: 1,
    passport: 810,
    task: "roleBrief",
    target: 3,
    advisors: [6],
  },
  {
    case: 31,
    employee: 31,
    status: "In progress",
    created: 27,
    updated: 4,
    passport: 1580,
    task: "documents",
    target: null,
    advisors: [6],
  },
  {
    case: 32,
    employee: 32,
    status: "Filed",
    created: 73,
    filed: 28,
    updated: 8,
    passport: 1380,
    advisors: [3],
  },
  {
    case: 33,
    employee: 33,
    status: "Approved",
    created: 612,
    filed: 564,
    approved: 521,
    updated: 12,
    expires: 209,
    passport: 960,
    advisors: [6],
  },
  {
    case: 34,
    employee: 34,
    status: "Pre-assessment",
    created: 6,
    updated: 2,
    passport: 1510,
    task: "missingCv",
    target: 4,
    advisors: [6],
  },
  {
    case: 35,
    employee: 35,
    status: "In progress",
    created: 42,
    updated: 3,
    passport: 1710,
    task: "employerReview",
    target: 9,
    advisors: [3],
  },
  {
    case: 50,
    employee: 70,
    status: "RFE Issued",
    created: 118,
    filed: 83,
    updated: 6,
    passport: 1230,
    task: "rfe",
    target: 10,
    advisors: [3, 6],
  },
  {
    case: 51,
    employee: 71,
    status: "Approved",
    created: 742,
    filed: 700,
    approved: 668,
    updated: 5,
    expires: 62,
    passport: 1060,
    advisors: [6],
  },
  {
    case: 52,
    employee: 72,
    status: "Approved",
    created: 421,
    filed: 380,
    approved: 331,
    updated: 18,
    expires: 721,
    passport: 1350,
    advisors: [6],
  },
  {
    case: 53,
    employee: 73,
    status: "Filed",
    created: 54,
    filed: 13,
    updated: 3,
    passport: 1670,
    advisors: [6],
  },
  {
    case: 60,
    employee: 60,
    status: "Approved",
    created: 278,
    filed: 239,
    approved: 191,
    updated: 4,
    expires: 539,
    passport: 45,
    task: "passport",
    target: 7,
    advisors: [3],
  },
  {
    case: 61,
    employee: 61,
    status: "In progress",
    created: 22,
    updated: 2,
    passport: null,
    task: "documents",
    target: 5,
    advisors: [3],
  },
  {
    case: 62,
    employee: 62,
    status: "Filed",
    created: 104,
    filed: 67,
    updated: 43,
    passport: 1410,
    task: "statusCheck",
    target: -1,
    advisors: [6],
  },
  {
    case: 63,
    employee: 63,
    status: "In progress",
    created: 52,
    updated: 37,
    passport: null,
    task: "documents",
    target: -3,
    advisors: [3],
  },
  {
    case: 64,
    employee: 74,
    status: "In progress",
    created: 46,
    updated: 33,
    passport: null,
    task: "documents",
    target: 2,
    advisors: [6],
  },
  // Existing approval and a new renewal are separate cases belonging to the same employee.
  {
    case: 100,
    employee: 10,
    status: "In progress",
    created: 21,
    updated: 2,
    task: "draft",
    target: 4,
    advisors: [3],
  },
  {
    case: 101,
    employee: 71,
    status: "Pre-assessment",
    created: 8,
    updated: 1,
    task: "assessment",
    target: 3,
    advisors: [6],
  },
];
