/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root";
import { Route as IndexRouteImport } from "./routes/index";
import { Route as MyCasesRouteRouteImport } from "./routes/my-cases/route";
import { Route as OverviewRouteRouteImport } from "./routes/overview/route";
import { Route as PreAssessmentsRouteImport } from "./routes/pre-assessments";
import { Route as ReportingAnalyticsRouteImport } from "./routes/reporting-analytics";
import { Route as MyCasesIndexRouteImport } from "./routes/my-cases/index";
import { Route as MyCasesCaseIdRouteImport } from "./routes/my-cases/$caseId";
import { Route as MyCasesAllRouteImport } from "./routes/my-cases/all";
import { Route as MyCasesApprovedRouteImport } from "./routes/my-cases/approved";
import { Route as MyCasesFiledRouteImport } from "./routes/my-cases/filed";
import { Route as MyCasesInProgressRouteImport } from "./routes/my-cases/in-progress";
import { Route as MyCasesPreAssessmentRouteImport } from "./routes/my-cases/pre-assessment";
import { Route as OverviewIndexRouteImport } from "./routes/overview/index";
import { Route as OverviewCaseIdRouteImport } from "./routes/overview/$caseId";

const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any);
const MyCasesRouteRoute = MyCasesRouteRouteImport.update({
  id: "/my-cases",
  path: "/my-cases",
  getParentRoute: () => rootRouteImport,
} as any);
const OverviewRouteRoute = OverviewRouteRouteImport.update({
  id: "/overview",
  path: "/overview",
  getParentRoute: () => rootRouteImport,
} as any);
const PreAssessmentsRoute = PreAssessmentsRouteImport.update({
  id: "/pre-assessments",
  path: "/pre-assessments",
  getParentRoute: () => rootRouteImport,
} as any);
const ReportingAnalyticsRoute = ReportingAnalyticsRouteImport.update({
  id: "/reporting-analytics",
  path: "/reporting-analytics",
  getParentRoute: () => rootRouteImport,
} as any);
const MyCasesIndexRoute = MyCasesIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => MyCasesRouteRoute,
} as any);
const MyCasesCaseIdRoute = MyCasesCaseIdRouteImport.update({
  id: "/$caseId",
  path: "/$caseId",
  getParentRoute: () => MyCasesRouteRoute,
} as any);
const MyCasesAllRoute = MyCasesAllRouteImport.update({
  id: "/all",
  path: "/all",
  getParentRoute: () => MyCasesRouteRoute,
} as any);
const MyCasesApprovedRoute = MyCasesApprovedRouteImport.update({
  id: "/approved",
  path: "/approved",
  getParentRoute: () => MyCasesRouteRoute,
} as any);
const MyCasesFiledRoute = MyCasesFiledRouteImport.update({
  id: "/filed",
  path: "/filed",
  getParentRoute: () => MyCasesRouteRoute,
} as any);
const MyCasesInProgressRoute = MyCasesInProgressRouteImport.update({
  id: "/in-progress",
  path: "/in-progress",
  getParentRoute: () => MyCasesRouteRoute,
} as any);
const MyCasesPreAssessmentRoute = MyCasesPreAssessmentRouteImport.update({
  id: "/pre-assessment",
  path: "/pre-assessment",
  getParentRoute: () => MyCasesRouteRoute,
} as any);
const OverviewIndexRoute = OverviewIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => OverviewRouteRoute,
} as any);
const OverviewCaseIdRoute = OverviewCaseIdRouteImport.update({
  id: "/$caseId",
  path: "/$caseId",
  getParentRoute: () => OverviewRouteRoute,
} as any);

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute;
  "/my-cases": typeof MyCasesRouteRouteWithChildren;
  "/overview": typeof OverviewRouteRouteWithChildren;
  "/pre-assessments": typeof PreAssessmentsRoute;
  "/reporting-analytics": typeof ReportingAnalyticsRoute;
  "/my-cases/$caseId": typeof MyCasesCaseIdRoute;
  "/my-cases/all": typeof MyCasesAllRoute;
  "/my-cases/approved": typeof MyCasesApprovedRoute;
  "/my-cases/filed": typeof MyCasesFiledRoute;
  "/my-cases/in-progress": typeof MyCasesInProgressRoute;
  "/my-cases/pre-assessment": typeof MyCasesPreAssessmentRoute;
  "/overview/$caseId": typeof OverviewCaseIdRoute;
  "/my-cases/": typeof MyCasesIndexRoute;
  "/overview/": typeof OverviewIndexRoute;
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute;
  "/pre-assessments": typeof PreAssessmentsRoute;
  "/reporting-analytics": typeof ReportingAnalyticsRoute;
  "/my-cases/$caseId": typeof MyCasesCaseIdRoute;
  "/my-cases/all": typeof MyCasesAllRoute;
  "/my-cases/approved": typeof MyCasesApprovedRoute;
  "/my-cases/filed": typeof MyCasesFiledRoute;
  "/my-cases/in-progress": typeof MyCasesInProgressRoute;
  "/my-cases/pre-assessment": typeof MyCasesPreAssessmentRoute;
  "/overview/$caseId": typeof OverviewCaseIdRoute;
  "/my-cases": typeof MyCasesIndexRoute;
  "/overview": typeof OverviewIndexRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/": typeof IndexRoute;
  "/my-cases": typeof MyCasesRouteRouteWithChildren;
  "/overview": typeof OverviewRouteRouteWithChildren;
  "/pre-assessments": typeof PreAssessmentsRoute;
  "/reporting-analytics": typeof ReportingAnalyticsRoute;
  "/my-cases/$caseId": typeof MyCasesCaseIdRoute;
  "/my-cases/all": typeof MyCasesAllRoute;
  "/my-cases/approved": typeof MyCasesApprovedRoute;
  "/my-cases/filed": typeof MyCasesFiledRoute;
  "/my-cases/in-progress": typeof MyCasesInProgressRoute;
  "/my-cases/pre-assessment": typeof MyCasesPreAssessmentRoute;
  "/overview/$caseId": typeof OverviewCaseIdRoute;
  "/my-cases/": typeof MyCasesIndexRoute;
  "/overview/": typeof OverviewIndexRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | "/"
    | "/my-cases"
    | "/overview"
    | "/pre-assessments"
    | "/reporting-analytics"
    | "/my-cases/$caseId"
    | "/my-cases/all"
    | "/my-cases/approved"
    | "/my-cases/filed"
    | "/my-cases/in-progress"
    | "/my-cases/pre-assessment"
    | "/overview/$caseId"
    | "/my-cases/"
    | "/overview/";
  fileRoutesByTo: FileRoutesByTo;
  to:
    | "/"
    | "/pre-assessments"
    | "/reporting-analytics"
    | "/my-cases/$caseId"
    | "/my-cases/all"
    | "/my-cases/approved"
    | "/my-cases/filed"
    | "/my-cases/in-progress"
    | "/my-cases/pre-assessment"
    | "/overview/$caseId"
    | "/my-cases"
    | "/overview";
  id:
    | "__root__"
    | "/"
    | "/my-cases"
    | "/overview"
    | "/pre-assessments"
    | "/reporting-analytics"
    | "/my-cases/$caseId"
    | "/my-cases/all"
    | "/my-cases/approved"
    | "/my-cases/filed"
    | "/my-cases/in-progress"
    | "/my-cases/pre-assessment"
    | "/overview/$caseId"
    | "/my-cases/"
    | "/overview/";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  MyCasesRouteRoute: typeof MyCasesRouteRouteWithChildren;
  OverviewRouteRoute: typeof OverviewRouteRouteWithChildren;
  PreAssessmentsRoute: typeof PreAssessmentsRoute;
  ReportingAnalyticsRoute: typeof ReportingAnalyticsRoute;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/my-cases": {
      id: "/my-cases";
      path: "/my-cases";
      fullPath: "/my-cases";
      preLoaderRoute: typeof MyCasesRouteRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/overview": {
      id: "/overview";
      path: "/overview";
      fullPath: "/overview";
      preLoaderRoute: typeof OverviewRouteRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/pre-assessments": {
      id: "/pre-assessments";
      path: "/pre-assessments";
      fullPath: "/pre-assessments";
      preLoaderRoute: typeof PreAssessmentsRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/reporting-analytics": {
      id: "/reporting-analytics";
      path: "/reporting-analytics";
      fullPath: "/reporting-analytics";
      preLoaderRoute: typeof ReportingAnalyticsRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/my-cases/": {
      id: "/my-cases/";
      path: "/";
      fullPath: "/my-cases/";
      preLoaderRoute: typeof MyCasesIndexRouteImport;
      parentRoute: typeof MyCasesRouteRoute;
    };
    "/my-cases/$caseId": {
      id: "/my-cases/$caseId";
      path: "/$caseId";
      fullPath: "/my-cases/$caseId";
      preLoaderRoute: typeof MyCasesCaseIdRouteImport;
      parentRoute: typeof MyCasesRouteRoute;
    };
    "/my-cases/all": {
      id: "/my-cases/all";
      path: "/all";
      fullPath: "/my-cases/all";
      preLoaderRoute: typeof MyCasesAllRouteImport;
      parentRoute: typeof MyCasesRouteRoute;
    };
    "/my-cases/approved": {
      id: "/my-cases/approved";
      path: "/approved";
      fullPath: "/my-cases/approved";
      preLoaderRoute: typeof MyCasesApprovedRouteImport;
      parentRoute: typeof MyCasesRouteRoute;
    };
    "/my-cases/filed": {
      id: "/my-cases/filed";
      path: "/filed";
      fullPath: "/my-cases/filed";
      preLoaderRoute: typeof MyCasesFiledRouteImport;
      parentRoute: typeof MyCasesRouteRoute;
    };
    "/my-cases/in-progress": {
      id: "/my-cases/in-progress";
      path: "/in-progress";
      fullPath: "/my-cases/in-progress";
      preLoaderRoute: typeof MyCasesInProgressRouteImport;
      parentRoute: typeof MyCasesRouteRoute;
    };
    "/my-cases/pre-assessment": {
      id: "/my-cases/pre-assessment";
      path: "/pre-assessment";
      fullPath: "/my-cases/pre-assessment";
      preLoaderRoute: typeof MyCasesPreAssessmentRouteImport;
      parentRoute: typeof MyCasesRouteRoute;
    };
    "/overview/": {
      id: "/overview/";
      path: "/";
      fullPath: "/overview/";
      preLoaderRoute: typeof OverviewIndexRouteImport;
      parentRoute: typeof OverviewRouteRoute;
    };
    "/overview/$caseId": {
      id: "/overview/$caseId";
      path: "/$caseId";
      fullPath: "/overview/$caseId";
      preLoaderRoute: typeof OverviewCaseIdRouteImport;
      parentRoute: typeof OverviewRouteRoute;
    };
  }
}

interface MyCasesRouteRouteChildren {
  MyCasesCaseIdRoute: typeof MyCasesCaseIdRoute;
  MyCasesAllRoute: typeof MyCasesAllRoute;
  MyCasesApprovedRoute: typeof MyCasesApprovedRoute;
  MyCasesFiledRoute: typeof MyCasesFiledRoute;
  MyCasesInProgressRoute: typeof MyCasesInProgressRoute;
  MyCasesPreAssessmentRoute: typeof MyCasesPreAssessmentRoute;
  MyCasesIndexRoute: typeof MyCasesIndexRoute;
}

const MyCasesRouteRouteChildren: MyCasesRouteRouteChildren = {
  MyCasesCaseIdRoute: MyCasesCaseIdRoute,
  MyCasesAllRoute: MyCasesAllRoute,
  MyCasesApprovedRoute: MyCasesApprovedRoute,
  MyCasesFiledRoute: MyCasesFiledRoute,
  MyCasesInProgressRoute: MyCasesInProgressRoute,
  MyCasesPreAssessmentRoute: MyCasesPreAssessmentRoute,
  MyCasesIndexRoute: MyCasesIndexRoute,
};

const MyCasesRouteRouteWithChildren = MyCasesRouteRoute._addFileChildren(
  MyCasesRouteRouteChildren,
);

interface OverviewRouteRouteChildren {
  OverviewCaseIdRoute: typeof OverviewCaseIdRoute;
  OverviewIndexRoute: typeof OverviewIndexRoute;
}

const OverviewRouteRouteChildren: OverviewRouteRouteChildren = {
  OverviewCaseIdRoute: OverviewCaseIdRoute,
  OverviewIndexRoute: OverviewIndexRoute,
};

const OverviewRouteRouteWithChildren = OverviewRouteRoute._addFileChildren(
  OverviewRouteRouteChildren,
);

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MyCasesRouteRoute: MyCasesRouteRouteWithChildren,
  OverviewRouteRoute: OverviewRouteRouteWithChildren,
  PreAssessmentsRoute: PreAssessmentsRoute,
  ReportingAnalyticsRoute: ReportingAnalyticsRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
